name: wp-plugin-readme2md
description: Convert WordPress plugin readme.txt files to markdown format for better display on GitHub.

branding:
  icon: "file-text"
  color: "blue"

runs:
  using: composite
  steps:
    - name: Set Up PHP (Version 8.0)
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Run Readme Converter
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: php "$ACTION_PATH/scripts/ReadmeConverter.php"
